package ooga.model.api;

/**
 * An event generated by a sprite.
 */
public class SpriteEvent {
  private final ObservableSprite sender;
  private final EventType type;

  /**
   * Create a sprite event.
   * @param sender Sender sprite.
   * @param type Event type.
   */
  public SpriteEvent(ObservableSprite sender, EventType type) {
    this.sender = sender;
    this.type = type;
  }

  /**
   * Query sender.
   * @return sender
   */
  public ObservableSprite getSender() {
    return sender;
  }

  /**
   * Query type.
   * @return type
   */
  public EventType getEventType() {
    return type;
  }

  /**
   * Possible event types.
   */
  public enum EventType {
    /**
     * Costume change
     */
    TYPE_CHANGE,
    /**
     * Change in visibility.
     */
    VISIBILITY,
    /**
     * Rigid translation.
     */
    TRANSLATE,
    /**
     * Rigid rotation.
     */
    ROTATE
  }
}
